### ISSUE TITLE
simle inference example 

### ISSUE THREAD

**Issue by fritol** [MCG-NJU/SGM-VFI#1]
can you put a simple inference example for arbitrary key frame set
or low framerate video input?

**Comment by lcxrocks** [comment]
Thank you for your attention. While this topic is beyond the scope of this repository's discussion, implementing it shouldn't be difficult. If you're in a hurry, you can refer to [RIFE](https://github.com/hzwer/ECCV2022-RIFE/blob/main/inference_video.py) and [FILM](https://github.com/google-research/frame-interpolation?tab=readme-ov-file#many-in-between-frames-interpolation), both of which offer excellent resources containing relevant code. Alternatively, we may release some relevant inference code soon.

**Comment by lcxrocks** [comment]
Thank you for your attention. While this topic is beyond our repo's discussion, implementing it shouldn't be difficult. Besides our demo inference code [`demo_2x.py`](https://github.com/MCG-NJU/SGM-VFI/blob/main/demo_2x.py), you can refer to [RIFE](https://github.com/hzwer/ECCV2022-RIFE/blob/main/inference_video.py) and [FILM](https://github.com/google-research/frame-interpolation?tab=readme-ov-file#many-in-between-frames-interpolation); they are both awesome works which contain the relevant code you need.
