### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by pengjunxing** [MCG-NJU/SGM-VFI#2]
Hi! Could you please tell me where can i get datasets of  XTest and Xiph. Thanks!

**Comment by lcxrocks** [comment]
You could refer to [here](https://github.com/sniklaus/softmax-splatting/blob/5ed33989bdfba48b093461a582df92b437e57ab4/benchmark_xiph.py#L20) for Xiph and [here](https://www.dropbox.com/scl/fo/88aarlg0v72dm8kvvwppe/AHxNqDye4_VMfqACzZNy5rU?rlkey=a2hgw60sv5prq3uaep2metxcn&e=1&dl=0) for X-TEST.
